use std::collections::HashMap;

use serde::Deserialize;

#[derive(Deserialize)]
pub(crate) struct BpeModel {
    /// Mapping from token to token ID. For byte-level BPE, the characters
    /// in the string represent byte values.
    pub vocab: HashMap<String, usize>,

    /// List of space-separated pairs of tokens to merge for BPE models.
    pub merges: Vec<String>,
}

#[derive(Deserialize)]
pub(crate) struct WordPieceModel {
    /// Mapping from token text to token ID.
    pub vocab: HashMap<String, usize>,
}

#[derive(Deserialize)]
#[serde(tag = "type")]
pub(crate) enum Model {
    #[serde(rename = "BPE")]
    Bpe(BpeModel),
    WordPiece(WordPieceModel),
}

/// Structure of the `tokenizers.json` files generated by Hugging Face
/// tokenizers [^1].
///
/// [^1]: https://github.com/huggingface/tokenizers
#[derive(Deserialize)]
pub(crate) struct TokenizerJson {
    pub model: Model,
}

pub fn from_json(json: &str) -> Result<TokenizerJson, serde_json::Error> {
    serde_json::from_str(json)
}
