use std::collections::HashMap;

use serde::Deserialize;

#[derive(Deserialize)]
pub(crate) struct Model {
    /// Model type (eg. BPE, WordPiece, Unigram)
    pub model_type: String,

    /// Mapping from token text to token ID. For byte-level BPE, the characters
    /// in the string represent byte values.
    pub vocab: HashMap<String, usize>,

    /// List of space-separated pairs of tokens to merge for BPE models.
    pub merges: Vec<String>,
}

/// Structure of the `tokenizers.json` files generated by Hugging Face
/// tokenizers [^1].
///
/// [^1]: https://github.com/huggingface/tokenizers
#[derive(Deserialize)]
pub(crate) struct TokenizerJson {
    pub model: Model,
}

pub fn from_json(json: &str) -> Result<TokenizerJson, serde_json::Error> {
    serde_json::from_str(json)
}
