[package]
name = "rten-simd"
version = "0.26.0"
edition = "2024"
authors = ["Robert Knight"]
description = "Portable SIMD for stable Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/robertknight/rten"
repository = "https://github.com/robertknight/rten"
include = ["/src", "/README.md"]
rust-version = "1.94.0"

[lib]
crate-type = ["lib"]

[lints.clippy]
# See comments about `needless_range_loop` in root Cargo.toml.
needless_range_loop = "allow"
manual_memcpy = "allow"

[package.metadata.docs.rs]
# As of August 2026, docs.rs only builds x86_64 Linux by default. Add other
# supported architectures so their types appear.
additional-targets = ["aarch64-unknown-linux-gnu", "wasm32-unknown-unknown"]
# WASM SIMD support requires the `simd128` target feature to be enabled.
# Other targets ignore this flag with a warning.
rustdoc-args = ["-C", "target-feature=+simd128"]
