"""
Parse models in `.rten` format.

This is the inverse of the serialization performed by `rten_convert.converter`.
Models are returned using the same intermediate representation that is produced
when parsing ONNX models (see `rten_convert.graph`).

The `.rten` file format is described in `docs/rten-file-format.md` in the RTen
repository.
"""

import mmap
import struct
from dataclasses import fields
from functools import reduce
from operator import mul
from typing import Any, Optional, cast

import numpy as np

import rten_convert.schema_generated as sg
from rten_convert.errors import ConversionError
from rten_convert.graph import ConstantNode, Graph, Node, OperatorNode, ValueNode
from rten_convert.metadata import Metadata

HEADER_LEN = 32
"""Size of the header in V2 model files."""

MAGIC = b"RTEN"
"""Magic bytes at the start of V2 model files."""

SUPPORTED_VERSION = 2
"""Version of the V2 file format that this module can read."""


def _enum_names(enum: Any) -> dict[int, str]:
    """Return a map of value to name for an enum generated by flatc."""
    return {
        value: name
        for name, value in vars(enum).items()
        if not name.startswith("_") and isinstance(value, int)
    }


OPERATOR_TYPE_NAMES = _enum_names(sg.OperatorType)
"""Map of `sg.OperatorType` value to operator name."""

CONSTANT_DTYPES = {
    sg.ConstantDataType.Float32: np.float32,
    sg.ConstantDataType.Int32: np.int32,
    sg.ConstantDataType.Int8: np.int8,
    sg.ConstantDataType.UInt8: np.uint8,
}
"""Map of `sg.ConstantDataType` value to NumPy data type."""


def _str(value: Optional[str | bytes]) -> str:
    """Decode a string field read from a FlatBuffers model."""
    if value is None:
        return ""
    # Strings are read as bytes, although flatc annotates them as `str`.
    return value.decode() if isinstance(value, bytes) else value


def _camel_case(name: str) -> str:
    """Convert a snake_case name to the camelCase used by flatc."""
    first, *rest = name.split("_")
    return first + "".join(word.capitalize() for word in rest)


def is_rten_model(path: str) -> bool:
    """
    Return true if `path` is a model in `.rten` format.

    V2 models are identified by magic bytes at the start of the file. V1 models
    are bare FlatBuffers buffers which have no reliable identifier, so this
    returns false for them.
    """
    with open(path, "rb") as fp:
        return fp.read(len(MAGIC)) == MAGIC


def read_model(path: str) -> tuple[Graph, Metadata]:
    """
    Read a model in `.rten` format.

    :param path: Path to a V1 or V2 format `.rten` file
    :return: Tuple of (main graph, model metadata)
    """

    with open(path, "rb") as fp:
        tensor_data: Optional[memoryview] = None

        if fp.read(len(MAGIC)) == MAGIC:
            fp.seek(0)
            header = fp.read(HEADER_LEN)
            if len(header) < HEADER_LEN:
                raise ConversionError("Model header is truncated")
            _, version, model_offset, model_len, tensor_data_offset = struct.unpack(
                "<4sIQQQ", header
            )
            if version != SUPPORTED_VERSION:
                raise ConversionError(f"Unsupported model file version {version}")

            fp.seek(model_offset)
            model_data = fp.read(model_len)

            # Tensor data is memory-mapped rather than read, as it can be
            # larger than available memory. The mapping remains valid after the
            # file is closed, and is kept alive by the arrays that reference it.
            mapping = mmap.mmap(fp.fileno(), 0, access=mmap.ACCESS_READ)
            tensor_data = memoryview(mapping)[tensor_data_offset:]
        else:
            # V1 models consist of just the FlatBuffers data, with all tensor
            # data stored inline.
            fp.seek(0)
            model_data = fp.read()

    try:
        model = sg.ModelT.InitFromPackedBuf(model_data, 0)
    except Exception as ex:
        raise ConversionError(f"Unable to parse model: {ex}")

    if model.graph is None:
        raise ConversionError("Model has no graph")

    return (
        graph_from_flatbuffers(model.graph, tensor_data),
        metadata_from_flatbuffers(model.metadata),
    )


def metadata_from_flatbuffers(fb_metadata: Optional[sg.MetadataT]) -> Metadata:
    """Read model metadata from a FlatBuffers model."""

    metadata = Metadata()
    if fb_metadata is None:
        return metadata

    for field in fields(Metadata):
        value = getattr(fb_metadata, _camel_case(field.name))
        if value is not None:
            setattr(metadata, field.name, _str(value))
    return metadata


def graph_from_flatbuffers(
    fb_graph: sg.GraphT, tensor_data: Optional[memoryview]
) -> Graph:
    """
    Read a graph from a FlatBuffers model.

    :param fb_graph: Graph read from the model file
    :param tensor_data:
        Contents of the model's tensor data segment, or None if the model
        stores all tensor data inline.
    """

    nodes: list[Node] = []
    node: Node

    for index, fb_node in enumerate(fb_graph.nodes or []):
        name = _str(fb_node.name)
        try:
            match fb_node.dataType:
                case sg.NodeKind.ConstantNode:
                    node = _constant_node(
                        name, cast(sg.ConstantNodeT, fb_node.data), tensor_data
                    )
                case sg.NodeKind.OperatorNode:
                    node = _operator_node(
                        name, cast(sg.OperatorNodeT, fb_node.data), tensor_data
                    )
                case sg.NodeKind.ValueNode:
                    node = _value_node(name, cast(sg.ValueNodeT, fb_node.data))
                case other:
                    raise ConversionError(f"Unsupported node kind {other}")
        except ConversionError as ex:
            raise ConversionError(f'Error reading node "{name}" (index {index}): {ex}')
        nodes.append(node)

    return Graph(
        nodes=nodes,
        inputs=_node_ids(fb_graph.inputs),
        outputs=_node_ids(fb_graph.outputs),
        captures=_node_ids(fb_graph.captures)
        if fb_graph.captures is not None
        else None,
    )


def _node_ids(ids: Any) -> list[int]:
    """Convert a vector of node IDs read from a model to a list."""
    return [int(id_) for id_ in ids] if ids is not None else []


def _constant_node(
    name: str, fb_const: sg.ConstantNodeT, tensor_data: Optional[memoryview]
) -> ConstantNode:
    # The shape is a required field in the model schema.
    shape = [int(size) for size in cast(list[int], fb_const.shape)]
    n_elems = reduce(mul, shape, 1)

    if fb_const.dataOffset is not None:
        if tensor_data is None:
            raise ConversionError(
                "Constant references the tensor data segment, but the model has none"
            )
        dtype = CONSTANT_DTYPES.get(cast(int, fb_const.dtype))
        if dtype is None:
            raise ConversionError(f"Unsupported constant data type {fb_const.dtype}")
        data = np.frombuffer(
            tensor_data, dtype=dtype, count=n_elems, offset=fb_const.dataOffset
        )
    elif fb_const.data is not None:
        data = np.asarray(fb_const.data.data)
    else:
        raise ConversionError("Constant has no data")

    return ConstantNode(name=name, shape=shape, data=data.reshape(shape))


def _operator_node(
    name: str, fb_op: sg.OperatorNodeT, tensor_data: Optional[memoryview]
) -> OperatorNode:
    op_type = OPERATOR_TYPE_NAMES.get(cast(int, fb_op.type))
    if op_type is None:
        raise ConversionError(f"Unknown operator type {fb_op.type}")

    # Replace subgraph attributes with the graph representation used by this
    # library.
    attrs = fb_op.attrs
    if attrs is not None:
        for field_name, value in vars(attrs).items():
            if isinstance(value, sg.GraphT):
                setattr(attrs, field_name, graph_from_flatbuffers(value, tensor_data))

    def node_id(id_: int) -> Optional[int]:
        # Negative IDs indicate missing optional inputs or unused outputs.
        return int(id_) if id_ >= 0 else None

    inputs = [
        node_id(id_) for id_ in (fb_op.inputs if fb_op.inputs is not None else [])
    ]
    outputs = [
        node_id(id_) for id_ in (fb_op.outputs if fb_op.outputs is not None else [])
    ]

    return OperatorNode(
        name=name, op_type=op_type, attrs=attrs, inputs=inputs, outputs=outputs
    )


def _value_node(name: str, fb_value: sg.ValueNodeT) -> ValueNode:
    shape: Optional[list[int | str]] = None
    if fb_value.shape is not None:
        shape = [
            _str(dim.name) if dim.name is not None else int(dim.value)
            for dim in fb_value.shape
        ]
    return ValueNode(name=name, shape=shape, dtype=fb_value.dtype)
