name: Zizmor

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable

      - name: Install Zizmor
        run: cargo install --locked zizmor

      - name: Run Zizmor
        run: zizmor --format sarif --output zizmor.sarif .github/workflows

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@397b4764c5bc24305eb8b7267d26b1f20ed9f986 # v3.30.4
        with:
          sarif_file: zizmor.sarif